document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'utf-8\'>");
document.writeln("		<meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("		<meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("		<link href=\'https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css\' rel=\'stylesheet\'>");
document.writeln("		<title></title>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->");
document.writeln("		    <script src=\'https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js\'></script>");
document.writeln("		    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->");
document.writeln("		    <script src=\'https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js\'></script>");
document.writeln("		    <nav class=\'navbar navbar-default\'>");
document.writeln("		  <div class=\'container-fluid\'>");
document.writeln("		    <!-- Brand and toggle get grouped for better mobile display -->");
document.writeln("		    <div class=\'navbar-header\'>");
document.writeln("		      <button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#bs-example-navbar-collapse-1\' aria-expanded=\'false\'>");
document.writeln("		        <span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("		        <span class=\'icon-bar\'></span>");
document.writeln("		        <span class=\'icon-bar\'></span>");
document.writeln("		        <span class=\'icon-bar\'></span>");
document.writeln("		      </button>");
document.writeln("		      <a class=\'navbar-brand\' href=\'#\'>商城管理系统</a>");
document.writeln("		    </div>");
document.writeln("		");
document.writeln("		    <!-- Collect the nav links, forms, and other content for toggling -->");
document.writeln("		    <div class=\'collapse navbar-collapse\' id=\'bs-example-navbar-collapse-1\'>");
document.writeln("		      <ul class=\'nav navbar-nav\'>");
document.writeln("		        <li class=\'dropdown\'>");
document.writeln("		          <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>商品管理 <span class=\'caret\'></span></a>");
document.writeln("		          <ul class=\'dropdown-menu\'>");
document.writeln("		            <li><a href=\'goods.html'>商品信息管理</a></li>");
document.writeln("		            <li role=\'separator\' class=\'divider\'></li>");
document.writeln("		            <li><a href=\'category.html'>商品分类管理</a></li>");
document.writeln("		            <li role=\'separator\' class=\'divider\'></li>");
document.writeln("		            <li><a href=\'comment.html'>商品评论管理</a></li>");
document.writeln("		          </ul>");
document.writeln("		        </li>");
document.writeln("		      </ul>");
document.writeln("		      <ul class=\'nav navbar-nav\'>");
document.writeln("		        <li class=\'dropdown\'>");
document.writeln("		          <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>订单管理 <span class=\'caret\'></span></a>");
document.writeln("		          <ul class=\'dropdown-menu\'>");
document.writeln("		            <li><a href=\'unDeliveryOrder.html\'>未发货订单管理</a></li>");
document.writeln("		            <li role=\'separator\' class=\'divider\'></li>");
document.writeln("		            <li><a href=\'orderRefund.html\'>退款订单管理</a></li>");
document.writeln("		            <li role=\'separator\' class=\'divider\'></li>");
document.writeln("		            <li><a href=\'order.html\'>订单总览</a></li>");
document.writeln("		          </ul>");
document.writeln("		        </li>");
document.writeln("		      </ul>");
document.writeln("		      <ul class=\'nav navbar-nav\'>");
document.writeln("		        <li class=\'dropdown\'>");
document.writeln("		          <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>人事管理 <span class=\'caret\'></span></a>");
document.writeln("		          <ul class=\'dropdown-menu\'>");
document.writeln("		            <li><a href=\'user.html'>用户管理</a></li>");
document.writeln("		            <li role=\'separator\' class=\'divider\'></li>");
document.writeln("		            <li><a href=\'admin.html\'>管理员管理</a></li>");
document.writeln("		          </ul>");
document.writeln("		        </li>");
document.writeln("		      </ul>");
document.writeln("		      <ul class=\'nav navbar-nav\'>");
document.writeln("		        <li class=\'dropdown\'>");
document.writeln("		          <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>其他 <span class=\'caret\'></span></a>");
document.writeln("		          <ul class=\'dropdown-menu\'>");
document.writeln("		            <li><a href=\'userAdvise.html'>用户反馈管理</a></li>");
document.writeln("		          </ul>");
document.writeln("		        </li>");
document.writeln("		      </ul>");
document.writeln("		      <ul class=\'nav navbar-nav navbar-right\'>");
document.writeln("		        <li class=\'dropdown\'>");
document.writeln("		          <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>设置 <span class=\'caret\'></span></a>");
document.writeln("		          <ul class=\'dropdown-menu\'>");
document.writeln("		            <li><a href=\'login.html'>退出登录</a></li>");
document.writeln("		          </ul>");
document.writeln("		        </li>");
document.writeln("		      </ul>");
document.writeln("		    </div><!-- /.navbar-collapse -->");
document.writeln("		  </div><!-- /.container-fluid -->");
document.writeln("		</nav>");
document.writeln("	</body>");
document.writeln("</html>");